name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest tox
        if [ -f osde2e/requirements.txt ]; then pip install -r osde2e/requirements.txt; fi
        if [ -f rosa/requirements.txt ]; then pip install -r osde2e/requirements.txt; fi
    - name: Tox
      run: |
        tox .
